name: CRON

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
            persist-credentials: false
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.ref }}
      - name: scrape run
        run: | 
          bash scan
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
